### ISSUE TITLE
 Recommendation pertaining to README File

### ISSUE THREAD

**Issue by gitdevjin** [AnhChienVu/VShell#1]
Hi Anh,
First of all, I read your README.md file; however, I didn't get the idea of what exactly the tool does. It says "to process input files and generate meaningful output", but I think it is a bit abstract, so I think it would be really helpful if the description is a bit more detailed : )

**Comment by AnhChienVu** [comment]
Hi Hyunjin, nice to see read your feedback. Yeah, you're true. Currently, I just integrated AI to my app to do a simple thing as generating output based on the files passed in. It will read through all the files and provide an overview of file's content so that user don't even need to read the file from top to bottom, but still can get the general idea about what it is.
However, I will upgrade that so it will generate a specific output that will correspond with its main purpose
