### ISSUE TITLE
issue with code structure

### ISSUE THREAD

**Issue by gitdevjin** [AnhChienVu/VShell#10]
I think you have refactored your code.
If I am being honest, now it is really hard to understand the code,
and I cannot see what the standard or pattern of your refactoring was.
I think you can improve the code by changing the function name and the strucutre of files and codes.

**Comment by AnhChienVu** [comment]
Sorry for confusing you. I just created a new src folder that I wanted to put all the .js files in it. Initially, I wrote everything in 1 single file server.js, but I want to module my code and separate them into methods. I think the main reason that confused you because the file and function's name, which are not easy to guess what they do.

**Comment by gitdevjin** [comment]
You don't have to apologize. it's your style.
It was just difficult for me to understand.
