### ISSUE TITLE
The Tool not running with the commend provided in the instruction

### ISSUE THREAD

**Issue by gitdevjin** [AnhChienVu/VShell#3]
<img width="1090" alt="Screenshot 2024-09-12 at 7 27 05 PM" src="https://github.com/user-attachments/assets/3ba34528-a144-420d-aa5e-b955ab345417">
First, the commend `npm link` does not work.
I think it's using some symlink and I think you set it in your local machine.

Therefore, this commend `vshell ../test.txt` also does not work

<img width="368" alt="Screenshot 2024-09-12 at 7 29 39 PM" src="https://github.com/user-attachments/assets/322c96ea-232b-4d82-97eb-ce1392a6b2b2">

**Comment by AnhChienVu** [comment]
Sorry about confusing you. Because I use JavaScript with Node.js so when I run my app, I always had to type node server.js. And it doesn't make sense in terms of user, so for user they only need to type the app's name. So I just did some extra set-up that I forgot to include in README file. 
I already added all steps needed, so now you can follow those steps and you can run with its name: vshell
