### ISSUE TITLE
Issue With Running the Tool

### ISSUE THREAD

**Issue by gitdevjin** [AnhChienVu/VShell#7]
I think something has changed, and now it doesn't work with the commend `node server.js <file>`
it gives the following error:
<img width="651" alt="Screenshot 2024-09-19 at 9 13 12 AM" src="https://github.com/user-attachments/assets/7205d2f9-f62d-4a76-91d3-7859d4169be4">

And also
`vshell file_name(s) <arguements>`
this commend is still not working

It only works with the following commend
`npm start ../test.txt`

**Comment by AnhChienVu** [comment]
Yesterday, I structured my source code to put all the js file to the src folder, including the server.js. That's why you cannot run it without setting the symlink again. 
So ideally, you should pull my repo to get the updated version, then follow the Usage section in my README file. Then everything will work.
If it doesn't just let me know the issue
